# Generated by Django 6.0.6 on 2026-06-05 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('crop_name', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('image', models.ImageField(upload_to='crop_problems/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('crop_problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmer_support.cropproblem')),
            ],
        ),
    ]
