# Generated by Django 6.0.5 on 2026-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_support', '0003_cropproblemguide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropproblemguide',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='cropproblemguide',
            name='causes',
            field=models.TextField(blank=True, help_text='Enter one cause per line'),
        ),
        migrations.AddField(
            model_name='cropproblemguide',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cropproblemguide',
            name='expert_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cropproblemguide',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_problem_guides/hero/'),
        ),
    ]
