# Generated by Django 6.0.6 on 2026-06-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Crop Advisory', 'Crop Advisory'), ('Soil Testing', 'Soil Testing'), ('Disease Identification', 'Disease Identification'), ('Plant Doctor', 'Plant Doctor'), ('Farmer Consultation', 'Farmer Consultation')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('crop_name', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('image', models.ImageField(upload_to='service_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
