# Generated by Django 6.0.6 on 2026-06-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='benefits',
            field=models.TextField(blank=True, help_text='Enter one benefit per line'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='why_choose',
            field=models.TextField(blank=True),
        ),
    ]
