# Generated by Django 6.0.6 on 2026-06-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
