# Generated by Django 6.0.5 on 2026-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicerequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinfo',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='features',
            field=models.TextField(blank=True, help_text='Enter one feature per line'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='hero_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_hero_images/'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='process_steps',
            field=models.TextField(blank=True, help_text='Enter one process step per line'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='related_services',
            field=models.ManyToManyField(blank=True, to='services.serviceinfo'),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='requirements',
            field=models.TextField(blank=True, help_text='Enter one requirement per line'),
        ),
    ]
