# Generated by Django 6.0.6 on 2026-06-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero_background/'),
        ),
    ]
