# Generated by Django 6.0.6 on 2026-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sitesettings_hero_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero_background/mobile/'),
        ),
    ]
