# Generated by Django 6.0.6 on 2026-06-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_sitesettings_logo_alter_sitesettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/'),
        ),
    ]
