# Generated by Django 6.0.6 on 2026-06-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_footersettings_delete_whychooseus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(default='© AgroSthan', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_icon_1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_icon_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_icon_3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_icon_4',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_title_1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_title_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_title_3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='why_title_4',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='AgroSthan', max_length=100),
            preserve_default=False,
        ),
    ]
