# Generated by Django 6.0.6 on 2026-06-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_footersettings_whychooseus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('identity_photo_upload', models.ImageField(upload_to='consultant_identity_docs/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='consultant_profiles/')),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active_status', models.BooleanField(default=False)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('identity_photo_upload', models.ImageField(upload_to='doctor_identity_docs/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active_status', models.BooleanField(default=False)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
