# Generated by Django 6.0.6 on 2026-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_consultant_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_title', models.CharField(default='Farmer/User', max_length=100)),
                ('farmer_description', models.TextField(default='Register as a Farmer and access products, machinery and consultations.')),
                ('farmer_icon', models.CharField(default='👨\u200d🌾', max_length=50)),
                ('doctor_title', models.CharField(default='Doctor', max_length=100)),
                ('doctor_description', models.TextField(default='Register as an Agriculture Doctor and manage farmer requests.')),
                ('doctor_icon', models.CharField(default='🩺', max_length=50)),
                ('consultant_title', models.CharField(default='Consultant', max_length=100)),
                ('consultant_description', models.TextField(default='Register as an Agriculture Consultant and provide expert guidance.')),
                ('consultant_icon', models.CharField(default='💼', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
