# Generated by Codex on 2026-06-18

from django.db import migrations, models


def create_default_roles(apps, schema_editor):

    Role = apps.get_model('accounts', 'Role')

    defaults = [
        {
            'name': 'Farmer',
            'slug': 'farmer',
            'description': (
                'Register as a Farmer and access products, orders, cart, '
                'machinery, and consultations.'
            ),
            'icon': '\U0001f33e',
            'register_url': 'register_farmer',
            'dashboard_url': 'dashboard',
        },
        {
            'name': 'Doctor',
            'slug': 'doctor',
            'description': (
                'Register as an Agriculture Doctor and manage farmer requests.'
            ),
            'icon': '\U0001fa7a',
            'register_url': 'doctor_register',
            'dashboard_url': 'doctor_dashboard',
        },
        {
            'name': 'Consultant',
            'slug': 'consultant',
            'description': (
                'Register as an Agriculture Consultant and provide expert '
                'guidance.'
            ),
            'icon': '\U0001f4bc',
            'register_url': 'consultant_register',
            'dashboard_url': 'consultant_dashboard',
        },
    ]

    for role_data in defaults:
        Role.objects.update_or_create(
            slug=role_data['slug'],
            defaults=role_data,
        )


def remove_default_roles(apps, schema_editor):

    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(slug__in=['farmer', 'doctor', 'consultant']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rolepagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='\U0001f464', max_length=50)),
                ('register_url', models.CharField(max_length=255)),
                ('dashboard_url', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(
            create_default_roles,
            remove_default_roles,
        ),
    ]
