# Generated by Django 6.0.6 on 2026-06-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_doctor_consultant_status'),
        ('accounts', '0013_role'),
    ]

    operations = [
    ]
