# Generated by Django 6.0.6 on 2026-06-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_0013_doctor_consultant_status_0013_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('consultant', 'Consultant')], max_length=20)),
                ('account_id', models.PositiveIntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='identity_edit_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='identity_edit_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
