# Generated by Django 6.0.6 on 2026-06-19 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _mark_existing_accounts_verified(apps, schema_editor):

    apps.get_model('accounts', 'Farmer').objects.update(email_verified=True, phone_verified=True)
    apps.get_model('accounts', 'Doctor').objects.update(email_verified=True, phone_verified=True)
    apps.get_model('accounts', 'Consultant').objects.update(email_verified=True, phone_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_identitychangerequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('doctor', 'Doctor'), ('consultant', 'Consultant'), ('admin', 'Admin')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='registration_otps/profile_photos/')),
                ('identity_photo_upload', models.ImageField(blank=True, null=True, upload_to='registration_otps/identity_docs/')),
                ('email_otp_hash', models.CharField(max_length=255)),
                ('phone_otp_hash', models.CharField(max_length=255)),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
                ('verify_attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agritech_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            code=_mark_existing_accounts_verified,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
