# Generated by Copilot on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_registrationotp_consultant_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepagesettings',
            name='role_name',
            field=models.CharField(default='Farmer/User', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='rolepagesettings',
            name='slug',
            field=models.SlugField(default='farmer-user', max_length=120, unique=True),
        ),
    ]
