# Generated by Django 6.0.6 on 2026-06-20 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rolepagesettings_role_name_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='consultant',
            name='certification_upload',
            field=models.FileField(blank=True, null=True, upload_to='consultant_certifications/'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultant',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consultant',
            name='qualification',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='consultant',
            name='specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='consultant',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certification_upload',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certifications/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('consultant', 'Consultant'), ('admin', 'Admin')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=140)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('textarea', 'Textarea')], default='text', max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('choices', models.TextField(blank=True, help_text='One option per line for dropdown, radio, or checkbox fields.')),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'sort_order', 'label'],
                'unique_together': {('role', 'key')},
            },
        ),
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('consultant', 'Consultant')], max_length=20)),
                ('account_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('requested_documents', 'Requested Additional Documents'), ('under_review', 'Marked Under Review')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
