# Generated by Django 6.0.5 on 2026-06-20 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def seed_access_codes(apps, schema_editor):
    AccessCode = apps.get_model('accounts', 'AccessCode')

    code_map = {
        'admin': getattr(settings, 'ADMIN_SECRET_CODE', 'AGROSTHAN2026'),
        'super_admin': getattr(settings, 'SUPER_ADMIN_SECRET_CODE', 'AGROSTHAN2026-SUPER'),
    }

    for code_type, raw_code in code_map.items():
        AccessCode.objects.update_or_create(
            code_type=code_type,
            defaults={
                'code_hash': make_password(raw_code),
            },
        )


def unseed_access_codes(apps, schema_editor):
    AccessCode = apps.get_model('accounts', 'AccessCode')
    AccessCode.objects.filter(code_type__in=['admin', 'super_admin']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('admin', 'Admin Access Code'), ('super_admin', 'Super Admin Access Code')], max_length=20, unique=True)),
                ('code_hash', models.CharField(max_length=255)),
                ('previous_code_hash', models.CharField(blank=True, default='', max_length=255)),
                ('rotation_count', models.PositiveIntegerField(default=0)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_access_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code_type'],
            },
        ),
        migrations.RunPython(seed_access_codes, unseed_access_codes),
    ]
