# Generated by Django 6.0.6 on 2026-06-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_tractorbooking_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractorbooking',
            name='machinery_type',
            field=models.CharField(choices=[('Tractor', 'Tractor'), ('Harvester', 'Harvester'), ('Rotavator', 'Rotavator'), ('Seed Drill', 'Seed Drill')], default='Tractor', max_length=50),
        ),
    ]
