# Generated by Django 6.0.6 on 2026-06-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_tractorbooking_machinery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='machinery/')),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
