# Generated by Django 6.0.6 on 2026-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0004_machinery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorbooking',
            name='machinery_type',
            field=models.CharField(choices=[('Tractor', 'Tractor'), ('Harvester', 'Harvester'), ('Rotavator', 'Rotavator'), ('Seed Drill', 'Seed Drill'), ('Drone', 'Drone')], default='Tractor', max_length=50),
        ),
    ]
