# Generated by Django 6.0.6 on 2026-06-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0006_machineryproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineryProduct',
        ),
    ]
