# Generated by Django 6.0.6 on 2026-06-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_consultant_doctor'),
        ('consultation', '0003_consultationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='assigned_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='accounts.consultant'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='consultant_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='doctor_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
