# Generated by Django 6.0.5 on 2026-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultationtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationtopic',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='consultationtopic',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultationtopic',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultationtopic',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='consultation_topics/hero/'),
        ),
    ]
