# Generated by Django 6.0.6 on 2026-06-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
