# Generated by Django 6.0.5 on 2026-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_review_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedvariety',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='seeds/hero/'),
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.seedvariety'),
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='specifications',
            field=models.TextField(blank=True, help_text='Enter one specification per line'),
        ),
        migrations.AddField(
            model_name='seedvariety',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
