# Generated by Django 6.0.5 on 2026-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_seedvariety_options_seedvariety_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
